[character]
success_symbol = "[ï„¸](bold green) "
error_symbol = "[ï„¸](bold red) "

[git_status]
#disabled = true
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
#stashed = "ğŸ“¦"
#modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[git_branch]
style = "208"
symbol = "îœ¥ "
