[character]
success_symbol = "[ï„¸](bold green) "
error_symbol = "[ï„¸](bold red) "

[git_status]
format='([$all_status$ahead_behind]($style) )'
conflicted = "ğŸ”¥$count"
ahead = "ğŸ˜$ahead_count"
behind = "ğŸ˜°$behind_count"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€$count"
stashed = "ïƒ‡ "
modified = "ï™ $count"
staged = '[ âš¡$count](green)'
renamed = "ğŸ´$count"
deleted = "ğŸ’€$count"

[git_branch]
style = "208"
symbol = "îœ¥ "
#symbol = "ï‚› "
